// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace PL.MVC.IOBalance.Areas.AdminManagement.Controllers
{
    public partial class DiscountController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected DiscountController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SaveDiscount()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveDiscount);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UpdateDiscount()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateDiscount);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteDiscount()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteDiscount);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetDiscount()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetDiscount);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public DiscountController Actions { get { return IOBALANCEMVC.AdminManagement.Discount; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "AdminManagement";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Discount";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Discount";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string SaveDiscount = "SaveDiscount";
            public readonly string UpdateDiscount = "UpdateDiscount";
            public readonly string DeleteDiscount = "DeleteDiscount";
            public readonly string GetDiscount = "GetDiscount";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string SaveDiscount = "SaveDiscount";
            public const string UpdateDiscount = "UpdateDiscount";
            public const string DeleteDiscount = "DeleteDiscount";
            public const string GetDiscount = "GetDiscount";
        }


        static readonly ActionParamsClass_SaveDiscount s_params_SaveDiscount = new ActionParamsClass_SaveDiscount();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveDiscount SaveDiscountParams { get { return s_params_SaveDiscount; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveDiscount
        {
            public readonly string dto = "dto";
        }
        static readonly ActionParamsClass_UpdateDiscount s_params_UpdateDiscount = new ActionParamsClass_UpdateDiscount();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpdateDiscount UpdateDiscountParams { get { return s_params_UpdateDiscount; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpdateDiscount
        {
            public readonly string dto = "dto";
        }
        static readonly ActionParamsClass_DeleteDiscount s_params_DeleteDiscount = new ActionParamsClass_DeleteDiscount();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteDiscount DeleteDiscountParams { get { return s_params_DeleteDiscount; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteDiscount
        {
            public readonly string discountId = "discountId";
            public readonly string branchId = "branchId";
        }
        static readonly ActionParamsClass_GetDiscount s_params_GetDiscount = new ActionParamsClass_GetDiscount();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetDiscount GetDiscountParams { get { return s_params_GetDiscount; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetDiscount
        {
            public readonly string request = "request";
            public readonly string searchModel = "searchModel";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _ListDiscount = "_ListDiscount";
                public readonly string _ModalEditDiscount = "_ModalEditDiscount";
                public readonly string _ModalSearchDiscount = "_ModalSearchDiscount";
                public readonly string _NewDiscount = "_NewDiscount";
                public readonly string Index = "Index";
            }
            public readonly string _ListDiscount = "~/Areas/AdminManagement/Views/Discount/_ListDiscount.cshtml";
            public readonly string _ModalEditDiscount = "~/Areas/AdminManagement/Views/Discount/_ModalEditDiscount.cshtml";
            public readonly string _ModalSearchDiscount = "~/Areas/AdminManagement/Views/Discount/_ModalSearchDiscount.cshtml";
            public readonly string _NewDiscount = "~/Areas/AdminManagement/Views/Discount/_NewDiscount.cshtml";
            public readonly string Index = "~/Areas/AdminManagement/Views/Discount/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_DiscountController : PL.MVC.IOBalance.Areas.AdminManagement.Controllers.DiscountController
    {
        public T4MVC_DiscountController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SaveDiscountOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, PL.Business.Dto.IOBalance.DiscountDto dto);

        [NonAction]
        public override System.Web.Mvc.ActionResult SaveDiscount(PL.Business.Dto.IOBalance.DiscountDto dto)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveDiscount);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "dto", dto);
            SaveDiscountOverride(callInfo, dto);
            return callInfo;
        }

        [NonAction]
        partial void UpdateDiscountOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, PL.Business.Dto.IOBalance.DiscountDto dto);

        [NonAction]
        public override System.Web.Mvc.ActionResult UpdateDiscount(PL.Business.Dto.IOBalance.DiscountDto dto)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateDiscount);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "dto", dto);
            UpdateDiscountOverride(callInfo, dto);
            return callInfo;
        }

        [NonAction]
        partial void DeleteDiscountOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int discountId, int branchId);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteDiscount(int discountId, int branchId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteDiscount);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "discountId", discountId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "branchId", branchId);
            DeleteDiscountOverride(callInfo, discountId, branchId);
            return callInfo;
        }

        [NonAction]
        partial void GetDiscountOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Kendo.Mvc.UI.DataSourceRequest request, PL.MVC.IOBalance.Areas.AdminManagement.Models.DiscountSearchModel searchModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetDiscount(Kendo.Mvc.UI.DataSourceRequest request, PL.MVC.IOBalance.Areas.AdminManagement.Models.DiscountSearchModel searchModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetDiscount);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "request", request);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchModel", searchModel);
            GetDiscountOverride(callInfo, request, searchModel);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
