// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace PL.MVC.IOBalance.Areas.AdminManagement.Controllers
{
    public partial class UnitController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected UnitController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SearchUnit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SearchUnit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SaveUnit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveUnit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UpdateUnit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateUnit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteUnit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteUnit);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public UnitController Actions { get { return IOBALANCEMVC.AdminManagement.Unit; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "AdminManagement";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Unit";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Unit";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string SearchUnit = "SearchUnit";
            public readonly string SaveUnit = "SaveUnit";
            public readonly string RefreshUnit = "RefreshUnit";
            public readonly string UpdateUnit = "UpdateUnit";
            public readonly string DeleteUnit = "DeleteUnit";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string SearchUnit = "SearchUnit";
            public const string SaveUnit = "SaveUnit";
            public const string RefreshUnit = "RefreshUnit";
            public const string UpdateUnit = "UpdateUnit";
            public const string DeleteUnit = "DeleteUnit";
        }


        static readonly ActionParamsClass_SearchUnit s_params_SearchUnit = new ActionParamsClass_SearchUnit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SearchUnit SearchUnitParams { get { return s_params_SearchUnit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SearchUnit
        {
            public readonly string searchModel = "searchModel";
        }
        static readonly ActionParamsClass_SaveUnit s_params_SaveUnit = new ActionParamsClass_SaveUnit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveUnit SaveUnitParams { get { return s_params_SaveUnit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveUnit
        {
            public readonly string dto = "dto";
        }
        static readonly ActionParamsClass_UpdateUnit s_params_UpdateUnit = new ActionParamsClass_UpdateUnit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpdateUnit UpdateUnitParams { get { return s_params_UpdateUnit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpdateUnit
        {
            public readonly string dto = "dto";
        }
        static readonly ActionParamsClass_DeleteUnit s_params_DeleteUnit = new ActionParamsClass_DeleteUnit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteUnit DeleteUnitParams { get { return s_params_DeleteUnit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteUnit
        {
            public readonly string unitId = "unitId";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _ListUnit = "_ListUnit";
                public readonly string _ModalEditUnit = "_ModalEditUnit";
                public readonly string _ModalSearchUnit = "_ModalSearchUnit";
                public readonly string _NewUnit = "_NewUnit";
                public readonly string Index = "Index";
            }
            public readonly string _ListUnit = "~/Areas/AdminManagement/Views/Unit/_ListUnit.cshtml";
            public readonly string _ModalEditUnit = "~/Areas/AdminManagement/Views/Unit/_ModalEditUnit.cshtml";
            public readonly string _ModalSearchUnit = "~/Areas/AdminManagement/Views/Unit/_ModalSearchUnit.cshtml";
            public readonly string _NewUnit = "~/Areas/AdminManagement/Views/Unit/_NewUnit.cshtml";
            public readonly string Index = "~/Areas/AdminManagement/Views/Unit/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_UnitController : PL.MVC.IOBalance.Areas.AdminManagement.Controllers.UnitController
    {
        public T4MVC_UnitController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SearchUnitOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, PL.MVC.IOBalance.Areas.AdminManagement.Models.UnitSearchModel searchModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult SearchUnit(PL.MVC.IOBalance.Areas.AdminManagement.Models.UnitSearchModel searchModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SearchUnit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchModel", searchModel);
            SearchUnitOverride(callInfo, searchModel);
            return callInfo;
        }

        [NonAction]
        partial void SaveUnitOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, PL.Business.Dto.IOBalance.UnitDto dto);

        [NonAction]
        public override System.Web.Mvc.ActionResult SaveUnit(PL.Business.Dto.IOBalance.UnitDto dto)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveUnit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "dto", dto);
            SaveUnitOverride(callInfo, dto);
            return callInfo;
        }

        [NonAction]
        partial void RefreshUnitOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult RefreshUnit()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RefreshUnit);
            RefreshUnitOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void UpdateUnitOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, PL.Business.Dto.IOBalance.UnitDto dto);

        [NonAction]
        public override System.Web.Mvc.ActionResult UpdateUnit(PL.Business.Dto.IOBalance.UnitDto dto)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateUnit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "dto", dto);
            UpdateUnitOverride(callInfo, dto);
            return callInfo;
        }

        [NonAction]
        partial void DeleteUnitOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int unitId);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteUnit(int unitId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteUnit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "unitId", unitId);
            DeleteUnitOverride(callInfo, unitId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
