// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace PL.MVC.IOBalance.Areas.OrderManagement.Controllers
{
    public partial class PurchaseOrderController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected PurchaseOrderController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddProduct()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddProduct);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SaveProductAndPurchaseOrder()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveProductAndPurchaseOrder);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UpdateProductDetails()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateProductDetails);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult VoidProductQty()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.VoidProductQty);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddQtyProduct()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddQtyProduct);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UploadProductImage()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UploadProductImage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetInventory()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetInventory);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ExtractInventory()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExtractInventory);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UploadInventory()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UploadInventory);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetBatchSummaries()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetBatchSummaries);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PurchaseOrderController Actions { get { return IOBALANCEMVC.OrderManagement.PurchaseOrder; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "OrderManagement";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "PurchaseOrder";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "PurchaseOrder";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string AddProduct = "AddProduct";
            public readonly string SaveProductAndPurchaseOrder = "SaveProductAndPurchaseOrder";
            public readonly string UpdateProductDetails = "UpdateProductDetails";
            public readonly string VoidProductQty = "VoidProductQty";
            public readonly string AddQtyProduct = "AddQtyProduct";
            public readonly string UploadProductImage = "UploadProductImage";
            public readonly string GetInventory = "GetInventory";
            public readonly string ExtractInventory = "ExtractInventory";
            public readonly string BatchInventory = "BatchInventory";
            public readonly string UploadInventory = "UploadInventory";
            public readonly string GetBatchSummaries = "GetBatchSummaries";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string AddProduct = "AddProduct";
            public const string SaveProductAndPurchaseOrder = "SaveProductAndPurchaseOrder";
            public const string UpdateProductDetails = "UpdateProductDetails";
            public const string VoidProductQty = "VoidProductQty";
            public const string AddQtyProduct = "AddQtyProduct";
            public const string UploadProductImage = "UploadProductImage";
            public const string GetInventory = "GetInventory";
            public const string ExtractInventory = "ExtractInventory";
            public const string BatchInventory = "BatchInventory";
            public const string UploadInventory = "UploadInventory";
            public const string GetBatchSummaries = "GetBatchSummaries";
        }


        static readonly ActionParamsClass_AddProduct s_params_AddProduct = new ActionParamsClass_AddProduct();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddProduct AddProductParams { get { return s_params_AddProduct; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddProduct
        {
            public readonly string dto = "dto";
        }
        static readonly ActionParamsClass_SaveProductAndPurchaseOrder s_params_SaveProductAndPurchaseOrder = new ActionParamsClass_SaveProductAndPurchaseOrder();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveProductAndPurchaseOrder SaveProductAndPurchaseOrderParams { get { return s_params_SaveProductAndPurchaseOrder; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveProductAndPurchaseOrder
        {
            public readonly string dto = "dto";
        }
        static readonly ActionParamsClass_UpdateProductDetails s_params_UpdateProductDetails = new ActionParamsClass_UpdateProductDetails();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpdateProductDetails UpdateProductDetailsParams { get { return s_params_UpdateProductDetails; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpdateProductDetails
        {
            public readonly string dto = "dto";
        }
        static readonly ActionParamsClass_VoidProductQty s_params_VoidProductQty = new ActionParamsClass_VoidProductQty();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_VoidProductQty VoidProductQtyParams { get { return s_params_VoidProductQty; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_VoidProductQty
        {
            public readonly string dto = "dto";
        }
        static readonly ActionParamsClass_AddQtyProduct s_params_AddQtyProduct = new ActionParamsClass_AddQtyProduct();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddQtyProduct AddQtyProductParams { get { return s_params_AddQtyProduct; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddQtyProduct
        {
            public readonly string dto = "dto";
        }
        static readonly ActionParamsClass_UploadProductImage s_params_UploadProductImage = new ActionParamsClass_UploadProductImage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UploadProductImage UploadProductImageParams { get { return s_params_UploadProductImage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UploadProductImage
        {
            public readonly string dto = "dto";
        }
        static readonly ActionParamsClass_GetInventory s_params_GetInventory = new ActionParamsClass_GetInventory();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetInventory GetInventoryParams { get { return s_params_GetInventory; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetInventory
        {
            public readonly string request = "request";
            public readonly string searchModel = "searchModel";
        }
        static readonly ActionParamsClass_ExtractInventory s_params_ExtractInventory = new ActionParamsClass_ExtractInventory();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ExtractInventory ExtractInventoryParams { get { return s_params_ExtractInventory; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ExtractInventory
        {
            public readonly string searchModel = "searchModel";
        }
        static readonly ActionParamsClass_UploadInventory s_params_UploadInventory = new ActionParamsClass_UploadInventory();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UploadInventory UploadInventoryParams { get { return s_params_UploadInventory; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UploadInventory
        {
            public readonly string file = "file";
        }
        static readonly ActionParamsClass_GetBatchSummaries s_params_GetBatchSummaries = new ActionParamsClass_GetBatchSummaries();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetBatchSummaries GetBatchSummariesParams { get { return s_params_GetBatchSummaries; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetBatchSummaries
        {
            public readonly string request = "request";
            public readonly string searchModel = "searchModel";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _BatchSummary = "_BatchSummary";
                public readonly string _BatchUpload = "_BatchUpload";
                public readonly string _FormEditProductImage = "_FormEditProductImage";
                public readonly string _ListInventory = "_ListInventory";
                public readonly string _ListInventoryKendo = "_ListInventoryKendo";
                public readonly string _ListOfOrders = "_ListOfOrders";
                public readonly string _ModalAddQtyProduct = "_ModalAddQtyProduct";
                public readonly string _ModalEditProductImage = "_ModalEditProductImage";
                public readonly string _ModalSearchBatchInventory = "_ModalSearchBatchInventory";
                public readonly string _ModalSearchProduct = "_ModalSearchProduct";
                public readonly string _ModalVoidQtyProduct = "_ModalVoidQtyProduct";
                public readonly string _PurchaseOrderEditForm = "_PurchaseOrderEditForm";
                public readonly string _PurchaseOrderForm = "_PurchaseOrderForm";
                public readonly string BatchInventory = "BatchInventory";
                public readonly string Index = "Index";
                public readonly string UploadProductImage = "UploadProductImage";
            }
            public readonly string _BatchSummary = "~/Areas/OrderManagement/Views/PurchaseOrder/_BatchSummary.cshtml";
            public readonly string _BatchUpload = "~/Areas/OrderManagement/Views/PurchaseOrder/_BatchUpload.cshtml";
            public readonly string _FormEditProductImage = "~/Areas/OrderManagement/Views/PurchaseOrder/_FormEditProductImage.cshtml";
            public readonly string _ListInventory = "~/Areas/OrderManagement/Views/PurchaseOrder/_ListInventory.cshtml";
            public readonly string _ListInventoryKendo = "~/Areas/OrderManagement/Views/PurchaseOrder/_ListInventoryKendo.cshtml";
            public readonly string _ListOfOrders = "~/Areas/OrderManagement/Views/PurchaseOrder/_ListOfOrders.cshtml";
            public readonly string _ModalAddQtyProduct = "~/Areas/OrderManagement/Views/PurchaseOrder/_ModalAddQtyProduct.cshtml";
            public readonly string _ModalEditProductImage = "~/Areas/OrderManagement/Views/PurchaseOrder/_ModalEditProductImage.cshtml";
            public readonly string _ModalSearchBatchInventory = "~/Areas/OrderManagement/Views/PurchaseOrder/_ModalSearchBatchInventory.cshtml";
            public readonly string _ModalSearchProduct = "~/Areas/OrderManagement/Views/PurchaseOrder/_ModalSearchProduct.cshtml";
            public readonly string _ModalVoidQtyProduct = "~/Areas/OrderManagement/Views/PurchaseOrder/_ModalVoidQtyProduct.cshtml";
            public readonly string _PurchaseOrderEditForm = "~/Areas/OrderManagement/Views/PurchaseOrder/_PurchaseOrderEditForm.cshtml";
            public readonly string _PurchaseOrderForm = "~/Areas/OrderManagement/Views/PurchaseOrder/_PurchaseOrderForm.cshtml";
            public readonly string BatchInventory = "~/Areas/OrderManagement/Views/PurchaseOrder/BatchInventory.cshtml";
            public readonly string Index = "~/Areas/OrderManagement/Views/PurchaseOrder/Index.cshtml";
            public readonly string UploadProductImage = "~/Areas/OrderManagement/Views/PurchaseOrder/UploadProductImage.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_PurchaseOrderController : PL.MVC.IOBalance.Areas.OrderManagement.Controllers.PurchaseOrderController
    {
        public T4MVC_PurchaseOrderController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void AddProductOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, PL.Business.Dto.IOBalance.ProductDto dto);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddProduct(PL.Business.Dto.IOBalance.ProductDto dto)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddProduct);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "dto", dto);
            AddProductOverride(callInfo, dto);
            return callInfo;
        }

        [NonAction]
        partial void SaveProductAndPurchaseOrderOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, PL.Business.Dto.IOBalance.ProductDto dto);

        [NonAction]
        public override System.Web.Mvc.ActionResult SaveProductAndPurchaseOrder(PL.Business.Dto.IOBalance.ProductDto dto)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveProductAndPurchaseOrder);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "dto", dto);
            SaveProductAndPurchaseOrderOverride(callInfo, dto);
            return callInfo;
        }

        [NonAction]
        partial void UpdateProductDetailsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, PL.Business.Dto.IOBalance.ProductDto dto);

        [NonAction]
        public override System.Web.Mvc.ActionResult UpdateProductDetails(PL.Business.Dto.IOBalance.ProductDto dto)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateProductDetails);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "dto", dto);
            UpdateProductDetailsOverride(callInfo, dto);
            return callInfo;
        }

        [NonAction]
        partial void VoidProductQtyOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, PL.Business.Dto.IOBalance.ProductDto dto);

        [NonAction]
        public override System.Web.Mvc.ActionResult VoidProductQty(PL.Business.Dto.IOBalance.ProductDto dto)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.VoidProductQty);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "dto", dto);
            VoidProductQtyOverride(callInfo, dto);
            return callInfo;
        }

        [NonAction]
        partial void AddQtyProductOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, PL.Business.Dto.IOBalance.ProductDto dto);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddQtyProduct(PL.Business.Dto.IOBalance.ProductDto dto)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddQtyProduct);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "dto", dto);
            AddQtyProductOverride(callInfo, dto);
            return callInfo;
        }

        [NonAction]
        partial void UploadProductImageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, PL.Business.Dto.IOBalance.ProductDto dto);

        [NonAction]
        public override System.Web.Mvc.ActionResult UploadProductImage(PL.Business.Dto.IOBalance.ProductDto dto)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UploadProductImage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "dto", dto);
            UploadProductImageOverride(callInfo, dto);
            return callInfo;
        }

        [NonAction]
        partial void GetInventoryOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Kendo.Mvc.UI.DataSourceRequest request, PL.MVC.IOBalance.Areas.OrderManagement.Models.ProductSearchModel searchModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetInventory(Kendo.Mvc.UI.DataSourceRequest request, PL.MVC.IOBalance.Areas.OrderManagement.Models.ProductSearchModel searchModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetInventory);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "request", request);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchModel", searchModel);
            GetInventoryOverride(callInfo, request, searchModel);
            return callInfo;
        }

        [NonAction]
        partial void ExtractInventoryOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, PL.MVC.IOBalance.Areas.OrderManagement.Models.ProductSearchModel searchModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult ExtractInventory(PL.MVC.IOBalance.Areas.OrderManagement.Models.ProductSearchModel searchModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExtractInventory);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchModel", searchModel);
            ExtractInventoryOverride(callInfo, searchModel);
            return callInfo;
        }

        [NonAction]
        partial void BatchInventoryOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult BatchInventory()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.BatchInventory);
            BatchInventoryOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void UploadInventoryOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Web.HttpPostedFileBase file);

        [NonAction]
        public override System.Web.Mvc.ActionResult UploadInventory(System.Web.HttpPostedFileBase file)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UploadInventory);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "file", file);
            UploadInventoryOverride(callInfo, file);
            return callInfo;
        }

        [NonAction]
        partial void GetBatchSummariesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Kendo.Mvc.UI.DataSourceRequest request, PL.MVC.IOBalance.Areas.OrderManagement.Models.BatchSummariesSearchModel searchModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetBatchSummaries(Kendo.Mvc.UI.DataSourceRequest request, PL.MVC.IOBalance.Areas.OrderManagement.Models.BatchSummariesSearchModel searchModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetBatchSummaries);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "request", request);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchModel", searchModel);
            GetBatchSummariesOverride(callInfo, request, searchModel);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
