// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace PL.MVC.IOBalance.Areas.OrderManagement.Controllers
{
    public partial class SalesOrderController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected SalesOrderController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddSalesOrder()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddSalesOrder);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ClickAddSalesOrder()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ClickAddSalesOrder);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SaveSalesOrder()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveSalesOrder);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SearchProductDetails()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SearchProductDetails);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SearchSavedSalesOrder()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SearchSavedSalesOrder);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ExtractReceipt()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExtractReceipt);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult RefreshProductDetails()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RefreshProductDetails);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult RefreshSavedSalesOrder()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RefreshSavedSalesOrder);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetProductList()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetProductList);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetSalesOrderList()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetSalesOrderList);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SearchProductPerBarCode()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SearchProductPerBarCode);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public SalesOrderController Actions { get { return IOBALANCEMVC.OrderManagement.SalesOrder; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "OrderManagement";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "SalesOrder";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "SalesOrder";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string AddSalesOrder = "AddSalesOrder";
            public readonly string ClickAddSalesOrder = "ClickAddSalesOrder";
            public readonly string SaveSalesOrder = "SaveSalesOrder";
            public readonly string SearchProductDetails = "SearchProductDetails";
            public readonly string SearchSavedSalesOrder = "SearchSavedSalesOrder";
            public readonly string ExtractReceipt = "ExtractReceipt";
            public readonly string RefreshProductDetails = "RefreshProductDetails";
            public readonly string RefreshSavedSalesOrder = "RefreshSavedSalesOrder";
            public readonly string GetProductList = "GetProductList";
            public readonly string GetSalesOrderList = "GetSalesOrderList";
            public readonly string SearchProductPerBarCode = "SearchProductPerBarCode";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string AddSalesOrder = "AddSalesOrder";
            public const string ClickAddSalesOrder = "ClickAddSalesOrder";
            public const string SaveSalesOrder = "SaveSalesOrder";
            public const string SearchProductDetails = "SearchProductDetails";
            public const string SearchSavedSalesOrder = "SearchSavedSalesOrder";
            public const string ExtractReceipt = "ExtractReceipt";
            public const string RefreshProductDetails = "RefreshProductDetails";
            public const string RefreshSavedSalesOrder = "RefreshSavedSalesOrder";
            public const string GetProductList = "GetProductList";
            public const string GetSalesOrderList = "GetSalesOrderList";
            public const string SearchProductPerBarCode = "SearchProductPerBarCode";
        }


        static readonly ActionParamsClass_AddSalesOrder s_params_AddSalesOrder = new ActionParamsClass_AddSalesOrder();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddSalesOrder AddSalesOrderParams { get { return s_params_AddSalesOrder; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddSalesOrder
        {
            public readonly string dto = "dto";
        }
        static readonly ActionParamsClass_ClickAddSalesOrder s_params_ClickAddSalesOrder = new ActionParamsClass_ClickAddSalesOrder();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ClickAddSalesOrder ClickAddSalesOrderParams { get { return s_params_ClickAddSalesOrder; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ClickAddSalesOrder
        {
            public readonly string productId = "productId";
            public readonly string branchId = "branchId";
        }
        static readonly ActionParamsClass_SaveSalesOrder s_params_SaveSalesOrder = new ActionParamsClass_SaveSalesOrder();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveSalesOrder SaveSalesOrderParams { get { return s_params_SaveSalesOrder; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveSalesOrder
        {
            public readonly string salesOrderDetailDto = "salesOrderDetailDto";
            public readonly string customerId = "customerId";
            public readonly string branchIdAdmin = "branchIdAdmin";
        }
        static readonly ActionParamsClass_SearchProductDetails s_params_SearchProductDetails = new ActionParamsClass_SearchProductDetails();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SearchProductDetails SearchProductDetailsParams { get { return s_params_SearchProductDetails; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SearchProductDetails
        {
            public readonly string searchModel = "searchModel";
        }
        static readonly ActionParamsClass_SearchSavedSalesOrder s_params_SearchSavedSalesOrder = new ActionParamsClass_SearchSavedSalesOrder();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SearchSavedSalesOrder SearchSavedSalesOrderParams { get { return s_params_SearchSavedSalesOrder; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SearchSavedSalesOrder
        {
            public readonly string searchModel = "searchModel";
        }
        static readonly ActionParamsClass_ExtractReceipt s_params_ExtractReceipt = new ActionParamsClass_ExtractReceipt();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ExtractReceipt ExtractReceiptParams { get { return s_params_ExtractReceipt; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ExtractReceipt
        {
            public readonly string salesOrderId = "salesOrderId";
        }
        static readonly ActionParamsClass_RefreshProductDetails s_params_RefreshProductDetails = new ActionParamsClass_RefreshProductDetails();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RefreshProductDetails RefreshProductDetailsParams { get { return s_params_RefreshProductDetails; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RefreshProductDetails
        {
            public readonly string searchModel = "searchModel";
        }
        static readonly ActionParamsClass_RefreshSavedSalesOrder s_params_RefreshSavedSalesOrder = new ActionParamsClass_RefreshSavedSalesOrder();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RefreshSavedSalesOrder RefreshSavedSalesOrderParams { get { return s_params_RefreshSavedSalesOrder; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RefreshSavedSalesOrder
        {
            public readonly string searchModel = "searchModel";
        }
        static readonly ActionParamsClass_GetProductList s_params_GetProductList = new ActionParamsClass_GetProductList();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetProductList GetProductListParams { get { return s_params_GetProductList; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetProductList
        {
            public readonly string request = "request";
            public readonly string searchModel = "searchModel";
        }
        static readonly ActionParamsClass_GetSalesOrderList s_params_GetSalesOrderList = new ActionParamsClass_GetSalesOrderList();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetSalesOrderList GetSalesOrderListParams { get { return s_params_GetSalesOrderList; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetSalesOrderList
        {
            public readonly string request = "request";
            public readonly string searchModel = "searchModel";
        }
        static readonly ActionParamsClass_SearchProductPerBarCode s_params_SearchProductPerBarCode = new ActionParamsClass_SearchProductPerBarCode();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SearchProductPerBarCode SearchProductPerBarCodeParams { get { return s_params_SearchProductPerBarCode; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SearchProductPerBarCode
        {
            public readonly string barCode = "barCode";
            public readonly string branchIdAdmin = "branchIdAdmin";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _ListOfOrderSales = "_ListOfOrderSales";
                public readonly string _ListOfProduct = "_ListOfProduct";
                public readonly string _ListOfProductKendo = "_ListOfProductKendo";
                public readonly string _ListOfSavedSalesOrder = "_ListOfSavedSalesOrder";
                public readonly string _ListOfSavedSalesOrderKendo = "_ListOfSavedSalesOrderKendo";
                public readonly string _ModalSearchProduct = "_ModalSearchProduct";
                public readonly string _ModalSearchSavedSalesOrder = "_ModalSearchSavedSalesOrder";
                public readonly string _SalesOrderForm = "_SalesOrderForm";
                public readonly string Index = "Index";
            }
            public readonly string _ListOfOrderSales = "~/Areas/OrderManagement/Views/SalesOrder/_ListOfOrderSales.cshtml";
            public readonly string _ListOfProduct = "~/Areas/OrderManagement/Views/SalesOrder/_ListOfProduct.cshtml";
            public readonly string _ListOfProductKendo = "~/Areas/OrderManagement/Views/SalesOrder/_ListOfProductKendo.cshtml";
            public readonly string _ListOfSavedSalesOrder = "~/Areas/OrderManagement/Views/SalesOrder/_ListOfSavedSalesOrder.cshtml";
            public readonly string _ListOfSavedSalesOrderKendo = "~/Areas/OrderManagement/Views/SalesOrder/_ListOfSavedSalesOrderKendo.cshtml";
            public readonly string _ModalSearchProduct = "~/Areas/OrderManagement/Views/SalesOrder/_ModalSearchProduct.cshtml";
            public readonly string _ModalSearchSavedSalesOrder = "~/Areas/OrderManagement/Views/SalesOrder/_ModalSearchSavedSalesOrder.cshtml";
            public readonly string _SalesOrderForm = "~/Areas/OrderManagement/Views/SalesOrder/_SalesOrderForm.cshtml";
            public readonly string Index = "~/Areas/OrderManagement/Views/SalesOrder/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_SalesOrderController : PL.MVC.IOBalance.Areas.OrderManagement.Controllers.SalesOrderController
    {
        public T4MVC_SalesOrderController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void AddSalesOrderOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, PL.Business.Dto.IOBalance.SalesOrderDetailDto dto);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddSalesOrder(PL.Business.Dto.IOBalance.SalesOrderDetailDto dto)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddSalesOrder);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "dto", dto);
            AddSalesOrderOverride(callInfo, dto);
            return callInfo;
        }

        [NonAction]
        partial void ClickAddSalesOrderOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long productId, int? branchId);

        [NonAction]
        public override System.Web.Mvc.ActionResult ClickAddSalesOrder(long productId, int? branchId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ClickAddSalesOrder);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "productId", productId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "branchId", branchId);
            ClickAddSalesOrderOverride(callInfo, productId, branchId);
            return callInfo;
        }

        [NonAction]
        partial void SaveSalesOrderOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Collections.Generic.List<PL.Business.Dto.IOBalance.SalesOrderDetailDto> salesOrderDetailDto, int customerId, int? branchIdAdmin);

        [NonAction]
        public override System.Web.Mvc.ActionResult SaveSalesOrder(System.Collections.Generic.List<PL.Business.Dto.IOBalance.SalesOrderDetailDto> salesOrderDetailDto, int customerId, int? branchIdAdmin)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveSalesOrder);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "salesOrderDetailDto", salesOrderDetailDto);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "customerId", customerId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "branchIdAdmin", branchIdAdmin);
            SaveSalesOrderOverride(callInfo, salesOrderDetailDto, customerId, branchIdAdmin);
            return callInfo;
        }

        [NonAction]
        partial void SearchProductDetailsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, PL.MVC.IOBalance.Areas.OrderManagement.Models.ProductSearchModel searchModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult SearchProductDetails(PL.MVC.IOBalance.Areas.OrderManagement.Models.ProductSearchModel searchModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SearchProductDetails);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchModel", searchModel);
            SearchProductDetailsOverride(callInfo, searchModel);
            return callInfo;
        }

        [NonAction]
        partial void SearchSavedSalesOrderOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, PL.MVC.IOBalance.Areas.OrderManagement.Models.SavedSalesOrderSearchModel searchModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult SearchSavedSalesOrder(PL.MVC.IOBalance.Areas.OrderManagement.Models.SavedSalesOrderSearchModel searchModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SearchSavedSalesOrder);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchModel", searchModel);
            SearchSavedSalesOrderOverride(callInfo, searchModel);
            return callInfo;
        }

        [NonAction]
        partial void ExtractReceiptOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long salesOrderId);

        [NonAction]
        public override System.Web.Mvc.ActionResult ExtractReceipt(long salesOrderId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExtractReceipt);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "salesOrderId", salesOrderId);
            ExtractReceiptOverride(callInfo, salesOrderId);
            return callInfo;
        }

        [NonAction]
        partial void RefreshProductDetailsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, PL.MVC.IOBalance.Areas.OrderManagement.Models.ProductSearchModel searchModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult RefreshProductDetails(PL.MVC.IOBalance.Areas.OrderManagement.Models.ProductSearchModel searchModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RefreshProductDetails);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchModel", searchModel);
            RefreshProductDetailsOverride(callInfo, searchModel);
            return callInfo;
        }

        [NonAction]
        partial void RefreshSavedSalesOrderOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, PL.MVC.IOBalance.Areas.OrderManagement.Models.SavedSalesOrderSearchModel searchModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult RefreshSavedSalesOrder(PL.MVC.IOBalance.Areas.OrderManagement.Models.SavedSalesOrderSearchModel searchModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RefreshSavedSalesOrder);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchModel", searchModel);
            RefreshSavedSalesOrderOverride(callInfo, searchModel);
            return callInfo;
        }

        [NonAction]
        partial void GetProductListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Kendo.Mvc.UI.DataSourceRequest request, PL.MVC.IOBalance.Areas.OrderManagement.Models.ProductSearchModel searchModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetProductList(Kendo.Mvc.UI.DataSourceRequest request, PL.MVC.IOBalance.Areas.OrderManagement.Models.ProductSearchModel searchModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetProductList);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "request", request);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchModel", searchModel);
            GetProductListOverride(callInfo, request, searchModel);
            return callInfo;
        }

        [NonAction]
        partial void GetSalesOrderListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Kendo.Mvc.UI.DataSourceRequest request, PL.MVC.IOBalance.Areas.OrderManagement.Models.SavedSalesOrderSearchModel searchModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetSalesOrderList(Kendo.Mvc.UI.DataSourceRequest request, PL.MVC.IOBalance.Areas.OrderManagement.Models.SavedSalesOrderSearchModel searchModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetSalesOrderList);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "request", request);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchModel", searchModel);
            GetSalesOrderListOverride(callInfo, request, searchModel);
            return callInfo;
        }

        [NonAction]
        partial void SearchProductPerBarCodeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string barCode, int? branchIdAdmin);

        [NonAction]
        public override System.Web.Mvc.ActionResult SearchProductPerBarCode(string barCode, int? branchIdAdmin)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SearchProductPerBarCode);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "barCode", barCode);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "branchIdAdmin", branchIdAdmin);
            SearchProductPerBarCodeOverride(callInfo, barCode, branchIdAdmin);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
