// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace PL.MVC.IOBalance.Areas.ReportManagement.Controllers
{
    public partial class InventorySalesController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected InventorySalesController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Index()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PurchaseOrderList()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PurchaseOrderList);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SalesOrderList()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SalesOrderList);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SalesReport()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SalesReport);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ExtractReportToExcel()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExtractReportToExcel);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ExtractReportPurchaseOrderToExcel()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExtractReportPurchaseOrderToExcel);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ExtractReportSalesOrderToExcel()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExtractReportSalesOrderToExcel);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ExtractReportSalesReportToExcel()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExtractReportSalesReportToExcel);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ExtractReportInventoryReportToExcel()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExtractReportInventoryReportToExcel);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetInventoryReport()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetInventoryReport);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public InventorySalesController Actions { get { return IOBALANCEMVC.ReportManagement.InventorySales; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "ReportManagement";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "InventorySales";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "InventorySales";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string PurchaseOrderList = "PurchaseOrderList";
            public readonly string SalesOrderList = "SalesOrderList";
            public readonly string SalesReport = "SalesReport";
            public readonly string InventoryReport = "InventoryReport";
            public readonly string ExtractReportToExcel = "ExtractReportToExcel";
            public readonly string ExtractReportPurchaseOrderToExcel = "ExtractReportPurchaseOrderToExcel";
            public readonly string ExtractReportSalesOrderToExcel = "ExtractReportSalesOrderToExcel";
            public readonly string ExtractReportSalesReportToExcel = "ExtractReportSalesReportToExcel";
            public readonly string ExtractReportInventoryReportToExcel = "ExtractReportInventoryReportToExcel";
            public readonly string GetInventoryReport = "GetInventoryReport";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string PurchaseOrderList = "PurchaseOrderList";
            public const string SalesOrderList = "SalesOrderList";
            public const string SalesReport = "SalesReport";
            public const string InventoryReport = "InventoryReport";
            public const string ExtractReportToExcel = "ExtractReportToExcel";
            public const string ExtractReportPurchaseOrderToExcel = "ExtractReportPurchaseOrderToExcel";
            public const string ExtractReportSalesOrderToExcel = "ExtractReportSalesOrderToExcel";
            public const string ExtractReportSalesReportToExcel = "ExtractReportSalesReportToExcel";
            public const string ExtractReportInventoryReportToExcel = "ExtractReportInventoryReportToExcel";
            public const string GetInventoryReport = "GetInventoryReport";
        }


        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_PurchaseOrderList s_params_PurchaseOrderList = new ActionParamsClass_PurchaseOrderList();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PurchaseOrderList PurchaseOrderListParams { get { return s_params_PurchaseOrderList; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PurchaseOrderList
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_SalesOrderList s_params_SalesOrderList = new ActionParamsClass_SalesOrderList();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SalesOrderList SalesOrderListParams { get { return s_params_SalesOrderList; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SalesOrderList
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_SalesReport s_params_SalesReport = new ActionParamsClass_SalesReport();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SalesReport SalesReportParams { get { return s_params_SalesReport; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SalesReport
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_ExtractReportToExcel s_params_ExtractReportToExcel = new ActionParamsClass_ExtractReportToExcel();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ExtractReportToExcel ExtractReportToExcelParams { get { return s_params_ExtractReportToExcel; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ExtractReportToExcel
        {
            public readonly string searchModel = "searchModel";
        }
        static readonly ActionParamsClass_ExtractReportPurchaseOrderToExcel s_params_ExtractReportPurchaseOrderToExcel = new ActionParamsClass_ExtractReportPurchaseOrderToExcel();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ExtractReportPurchaseOrderToExcel ExtractReportPurchaseOrderToExcelParams { get { return s_params_ExtractReportPurchaseOrderToExcel; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ExtractReportPurchaseOrderToExcel
        {
            public readonly string searchModel = "searchModel";
        }
        static readonly ActionParamsClass_ExtractReportSalesOrderToExcel s_params_ExtractReportSalesOrderToExcel = new ActionParamsClass_ExtractReportSalesOrderToExcel();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ExtractReportSalesOrderToExcel ExtractReportSalesOrderToExcelParams { get { return s_params_ExtractReportSalesOrderToExcel; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ExtractReportSalesOrderToExcel
        {
            public readonly string searchModel = "searchModel";
        }
        static readonly ActionParamsClass_ExtractReportSalesReportToExcel s_params_ExtractReportSalesReportToExcel = new ActionParamsClass_ExtractReportSalesReportToExcel();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ExtractReportSalesReportToExcel ExtractReportSalesReportToExcelParams { get { return s_params_ExtractReportSalesReportToExcel; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ExtractReportSalesReportToExcel
        {
            public readonly string searchModel = "searchModel";
        }
        static readonly ActionParamsClass_ExtractReportInventoryReportToExcel s_params_ExtractReportInventoryReportToExcel = new ActionParamsClass_ExtractReportInventoryReportToExcel();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ExtractReportInventoryReportToExcel ExtractReportInventoryReportToExcelParams { get { return s_params_ExtractReportInventoryReportToExcel; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ExtractReportInventoryReportToExcel
        {
            public readonly string searchModel = "searchModel";
        }
        static readonly ActionParamsClass_GetInventoryReport s_params_GetInventoryReport = new ActionParamsClass_GetInventoryReport();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetInventoryReport GetInventoryReportParams { get { return s_params_GetInventoryReport; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetInventoryReport
        {
            public readonly string request = "request";
            public readonly string searchModel = "searchModel";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _InventoryReport = "_InventoryReport";
                public readonly string _ModalSearchInventoryReport = "_ModalSearchInventoryReport";
                public readonly string Index = "Index";
                public readonly string InventoryReport = "InventoryReport";
                public readonly string PurchaseOrderList = "PurchaseOrderList";
                public readonly string SalesOrderList = "SalesOrderList";
                public readonly string SalesReport = "SalesReport";
            }
            public readonly string _InventoryReport = "~/Areas/ReportManagement/Views/InventorySales/_InventoryReport.cshtml";
            public readonly string _ModalSearchInventoryReport = "~/Areas/ReportManagement/Views/InventorySales/_ModalSearchInventoryReport.cshtml";
            public readonly string Index = "~/Areas/ReportManagement/Views/InventorySales/Index.cshtml";
            public readonly string InventoryReport = "~/Areas/ReportManagement/Views/InventorySales/InventoryReport.cshtml";
            public readonly string PurchaseOrderList = "~/Areas/ReportManagement/Views/InventorySales/PurchaseOrderList.cshtml";
            public readonly string SalesOrderList = "~/Areas/ReportManagement/Views/InventorySales/SalesOrderList.cshtml";
            public readonly string SalesReport = "~/Areas/ReportManagement/Views/InventorySales/SalesReport.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_InventorySalesController : PL.MVC.IOBalance.Areas.ReportManagement.Controllers.InventorySalesController
    {
        public T4MVC_InventorySalesController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, PL.MVC.IOBalance.Areas.ReportManagement.Models.ReportInventoryPerItemSearchModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index(PL.MVC.IOBalance.Areas.ReportManagement.Models.ReportInventoryPerItemSearchModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            IndexOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void PurchaseOrderListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, PL.MVC.IOBalance.Areas.ReportManagement.Models.ReportInventoryPerItemSearchModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult PurchaseOrderList(PL.MVC.IOBalance.Areas.ReportManagement.Models.ReportInventoryPerItemSearchModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PurchaseOrderList);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            PurchaseOrderListOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void SalesOrderListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, PL.MVC.IOBalance.Areas.ReportManagement.Models.ReportInventoryPerItemSearchModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult SalesOrderList(PL.MVC.IOBalance.Areas.ReportManagement.Models.ReportInventoryPerItemSearchModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SalesOrderList);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            SalesOrderListOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void SalesReportOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, PL.MVC.IOBalance.Areas.ReportManagement.Models.ReportInventoryPerItemSearchModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult SalesReport(PL.MVC.IOBalance.Areas.ReportManagement.Models.ReportInventoryPerItemSearchModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SalesReport);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            SalesReportOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void InventoryReportOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult InventoryReport()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.InventoryReport);
            InventoryReportOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ExtractReportToExcelOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, PL.MVC.IOBalance.Areas.ReportManagement.Models.ReportInventoryPerItemSearchModel searchModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult ExtractReportToExcel(PL.MVC.IOBalance.Areas.ReportManagement.Models.ReportInventoryPerItemSearchModel searchModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExtractReportToExcel);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchModel", searchModel);
            ExtractReportToExcelOverride(callInfo, searchModel);
            return callInfo;
        }

        [NonAction]
        partial void ExtractReportPurchaseOrderToExcelOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, PL.MVC.IOBalance.Areas.ReportManagement.Models.ReportInventoryPerItemSearchModel searchModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult ExtractReportPurchaseOrderToExcel(PL.MVC.IOBalance.Areas.ReportManagement.Models.ReportInventoryPerItemSearchModel searchModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExtractReportPurchaseOrderToExcel);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchModel", searchModel);
            ExtractReportPurchaseOrderToExcelOverride(callInfo, searchModel);
            return callInfo;
        }

        [NonAction]
        partial void ExtractReportSalesOrderToExcelOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, PL.MVC.IOBalance.Areas.ReportManagement.Models.ReportInventoryPerItemSearchModel searchModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult ExtractReportSalesOrderToExcel(PL.MVC.IOBalance.Areas.ReportManagement.Models.ReportInventoryPerItemSearchModel searchModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExtractReportSalesOrderToExcel);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchModel", searchModel);
            ExtractReportSalesOrderToExcelOverride(callInfo, searchModel);
            return callInfo;
        }

        [NonAction]
        partial void ExtractReportSalesReportToExcelOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, PL.MVC.IOBalance.Areas.ReportManagement.Models.ReportInventoryPerItemSearchModel searchModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult ExtractReportSalesReportToExcel(PL.MVC.IOBalance.Areas.ReportManagement.Models.ReportInventoryPerItemSearchModel searchModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExtractReportSalesReportToExcel);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchModel", searchModel);
            ExtractReportSalesReportToExcelOverride(callInfo, searchModel);
            return callInfo;
        }

        [NonAction]
        partial void ExtractReportInventoryReportToExcelOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, PL.MVC.IOBalance.Areas.ReportManagement.Models.ReportInventorySearchModel searchModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult ExtractReportInventoryReportToExcel(PL.MVC.IOBalance.Areas.ReportManagement.Models.ReportInventorySearchModel searchModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExtractReportInventoryReportToExcel);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchModel", searchModel);
            ExtractReportInventoryReportToExcelOverride(callInfo, searchModel);
            return callInfo;
        }

        [NonAction]
        partial void GetInventoryReportOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Kendo.Mvc.UI.DataSourceRequest request, PL.MVC.IOBalance.Areas.ReportManagement.Models.ReportInventorySearchModel searchModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetInventoryReport(Kendo.Mvc.UI.DataSourceRequest request, PL.MVC.IOBalance.Areas.ReportManagement.Models.ReportInventorySearchModel searchModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetInventoryReport);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "request", request);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchModel", searchModel);
            GetInventoryReportOverride(callInfo, request, searchModel);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
